services:
  - type: web
    name: obsidian-core-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: PORT
        value: 3000
      - key: PUBLIC_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: TWITCH_CLIENT_ID
        sync: false
      - key: TWITCH_CLIENT_SECRET
        sync: false
      - key: TWITCH_EVENTSUB_SECRET
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_TOKEN
        sync: false
      - key: OBS_URL
        sync: false
      - key: OBS_PASSWORD
        sync: false
